import React, { useState } from 'react';
import { 
  BookOpen, 
  Sparkles, 
  Stethoscope, 
  FileText, 
  Activity, 
  AlertCircle, 
  Pill, 
  CheckCircle2, 
  Calendar, 
  Download, 
  Share2, 
  Loader2,
  Info
} from 'lucide-react';
import { useHealth } from '../../context/HealthContext';
import { aiService } from '../../services/aiService';

export const HealthStoryPage = () => {
  const { stats, records, showToast } = useHealth();

  const [isGenerating, setIsGenerating] = useState(false);
  const [aiSummaryData, setAiSummaryData] = useState(null);

  const handleGenerateSummary = async () => {
    setIsGenerating(true);
    try {
      const summary = await aiService.generateHealthStorySummary(stats, records);
      setAiSummaryData(summary);
      showToast("Health Story Summary generated by AI");
    } finally {
      setIsGenerating(false);
    }
  };

  const milestones = [
    {
      month: "June 2026",
      title: "Initial Baseline & Allergy Evaluation",
      description: "First consultation with Dr. Sharma. Evaluated for seasonal allergic rhinitis. Baseline ECG and routine CBC test ordered.",
      tags: ["Dr. Sharma", "ECG", "Cetirizine 10mg"],
      badge: "Consultation"
    },
    {
      month: "July 2026",
      title: "Diagnostic Reports & Supplementation",
      description: "Follow-up visit. Low Vitamin D3 detected on lab work. Prescribed weekly Vitamin D3 60,000 IU. Lipid profile confirmed healthy cholesterol levels.",
      tags: ["Lipid Profile", "Vitamin D3 60K", "Normal Liver Function"],
      badge: "Diagnostics"
    },
    {
      month: "August 2026",
      title: "Gastric Flare-up & Adherence",
      description: "Experienced recurring upper abdominal burning and elevated blood pressure. Diagnosed with mild gastritis. Initiated Pantoprazole 40mg with noticeable recovery.",
      tags: ["Dr. Sharma", "Pantoprazole 40mg", "BP Stabilized 128/82"],
      badge: "Treatment"
    }
  ];

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold text-health-700 uppercase tracking-wider">
            <BookOpen className="w-4 h-4" />
            <span>Health Journey Recap</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mt-1">
            My Health Story
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            A comprehensive, human narrative of your health journey from January – August 2026.
          </p>
        </div>

        <button
          type="button"
          onClick={handleGenerateSummary}
          disabled={isGenerating}
          className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-tr from-health-600 to-teal-500 hover:from-health-700 hover:to-teal-600 text-white font-bold text-xs rounded-2xl shadow-md shadow-health-600/25 hover:shadow-lg transition-all"
        >
          {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
          <span>{isGenerating ? "Synthesizing Memory..." : "Generate AI Health Summary"}</span>
        </button>
      </div>

      {/* Overview Stat Counters */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3.5">
        <div className="bg-white rounded-3xl p-4 border border-slate-100 shadow-soft text-center">
          <div className="w-10 h-10 rounded-2xl bg-cyan-50 text-cyan-700 flex items-center justify-center mx-auto mb-2">
            <Stethoscope className="w-5 h-5" />
          </div>
          <h3 className="text-2xl font-bold text-slate-900">
            {stats?.doctorVisitsCount ?? records.filter(r => r.type === 'doctor_visit').length}
          </h3>
          <p className="text-xs font-medium text-slate-500">Doctor Visits</p>
        </div>

        <div className="bg-white rounded-3xl p-4 border border-slate-100 shadow-soft text-center">
          <div className="w-10 h-10 rounded-2xl bg-emerald-50 text-emerald-700 flex items-center justify-center mx-auto mb-2">
            <FileText className="w-5 h-5" />
          </div>
          <h3 className="text-2xl font-bold text-slate-900">
            {stats?.documentsCount ?? records.filter(r => r.type === 'document').length}
          </h3>
          <p className="text-xs font-medium text-slate-500">Documents</p>
        </div>

        <div className="bg-white rounded-3xl p-4 border border-slate-100 shadow-soft text-center">
          <div className="w-10 h-10 rounded-2xl bg-rose-50 text-rose-700 flex items-center justify-center mx-auto mb-2">
            <Activity className="w-5 h-5" />
          </div>
          <h3 className="text-2xl font-bold text-slate-900">
            {records.filter(r => ['blood_pressure', 'blood_sugar', 'weight', 'temperature', 'vitals'].includes(r.type)).length}
          </h3>
          <p className="text-xs font-medium text-slate-500">Recorded Vitals</p>
        </div>

        <div className="bg-white rounded-3xl p-4 border border-slate-100 shadow-soft text-center">
          <div className="w-10 h-10 rounded-2xl bg-orange-50 text-orange-700 flex items-center justify-center mx-auto mb-2">
            <AlertCircle className="w-5 h-5" />
          </div>
          <h3 className="text-2xl font-bold text-slate-900">
            {records.filter(r => r.type === 'symptom').length}
          </h3>
          <p className="text-xs font-medium text-slate-500">Symptoms</p>
        </div>

        <div className="bg-white rounded-3xl p-4 border border-slate-100 shadow-soft text-center col-span-2 sm:col-span-1">
          <div className="w-10 h-10 rounded-2xl bg-purple-50 text-purple-700 flex items-center justify-center mx-auto mb-2">
            <Pill className="w-5 h-5" />
          </div>
          <h3 className="text-2xl font-bold text-slate-900">
            {stats?.activeMedicinesCount ?? records.filter(r => r.type === 'medicine').length}
          </h3>
          <p className="text-xs font-medium text-slate-500">Medicines</p>
        </div>
      </div>

      {/* Generated AI Summary Box */}
      {aiSummaryData && (
        <div className="bg-gradient-to-br from-health-50 via-teal-50/60 to-white rounded-3xl p-6 sm:p-8 border border-health-200 shadow-soft-lg space-y-4 animate-slide-up">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-health-600" />
              <h3 className="text-base font-bold text-health-950">{aiSummaryData.title}</h3>
            </div>
            <span className="text-[11px] font-semibold text-health-700 bg-white px-3 py-1 rounded-xl border border-health-200 shadow-xs">
              Generated on {aiSummaryData.generatedAt}
            </span>
          </div>

          <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-line bg-white/90 p-5 rounded-2xl border border-health-100">
            {aiSummaryData.summary}
          </p>

          <div className="p-3.5 bg-emerald-50 rounded-2xl border border-emerald-200 text-xs text-emerald-900 font-medium">
            <span className="font-bold">Next Steps Recommendation: </span>
            {aiSummaryData.recommendation}
          </div>

          <div className="flex items-center justify-between pt-2">
            <span className="text-xs text-slate-400 italic">
              Verified from 52 recorded memory events
            </span>
            <div className="flex items-center gap-2">
              <button
                onClick={() => showToast("Health story downloaded (PDF mock)")}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-slate-700 bg-white hover:bg-slate-50 border border-slate-200 rounded-xl shadow-xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export PDF</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Chronological Milestone Highlights */}
      <div className="space-y-4">
        <h3 className="text-base font-bold text-slate-900 tracking-tight">
          Journey Highlights & Milestones
        </h3>

        <div className="relative pl-6 sm:pl-8 border-l-2 border-health-200 space-y-8 ml-4">
          {milestones.map((m, idx) => (
            <div key={idx} className="relative group">
              {/* Dot marker */}
              <div className="absolute -left-[31px] sm:-left-[39px] top-1.5 w-6 h-6 rounded-full bg-white border-4 border-health-600 shadow-sm" />

              <div className="bg-white rounded-3xl p-6 border border-slate-100 shadow-soft space-y-3 group-hover:border-health-300 transition-all">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <span className="text-xs font-extrabold text-health-800 bg-health-50 px-3 py-1 rounded-xl border border-health-200">
                    {m.month}
                  </span>
                  <span className="text-xs font-bold text-slate-400">
                    {m.badge}
                  </span>
                </div>

                <h4 className="text-lg font-bold text-slate-800 tracking-tight">
                  {m.title}
                </h4>

                <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
                  {m.description}
                </p>

                <div className="flex items-center gap-2 flex-wrap pt-1">
                  {m.tags.map((tag, tIdx) => (
                    <span key={tIdx} className="text-[11px] font-semibold text-slate-600 bg-slate-100 px-2.5 py-1 rounded-lg">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Medical Disclaimer */}
      <div className="p-4 bg-slate-100 rounded-3xl border border-slate-200 text-xs text-slate-500 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-slate-400 shrink-0 mt-0.5" />
        <div>
          <span className="font-bold text-slate-700">Clinical Disclaimer: </span>
          AI-generated health summaries are informational aids for communication and should always be verified with a qualified healthcare professional.
        </div>
      </div>
    </div>
  );
};
